INSERT INTO exercises (`title`,`idToken`, `content`, `status`, `category`,`weight`,`reps`,`sets`,`restTime`,`created_at`,`updated_at`)
VALUES ("Klękanie ze stepem i otwieranie klatki","klekanie-ze-stepem-i-otwieranie-klatki", NULL,"active",0,NULL,20,2,30,NOW(),NOW()),
("Rozruszanie nadgarstków i pleców","rozruszanie-nadgarstkow-i-plecow", NULL,"active",0,NULL,15,2,30,NOW(),NOW()),
("Przysiad dzielony","przysiad-dzielony", NULL,"active",0,NULL,15,2,0,NOW(),NOW()),
("Pajacyki","pajacyki", NULL,"active",0,NULL,20,1,30,NOW(),NOW()),
("Mosty biodrowe + aniołki na brzuchu + hollow body","mosty-biodrowe-aniolki-na-brzuchu-hollow-body", NULL,"active",0,NULL,20,2,30,NOW(),NOW()),
("Plank boczny + wirowanie ramionami","plank-boczny-wirowanie-ramionami", NULL,"active",0,NULL,15,2,0,NOW(),NOW()),
("Przysiad Goblet","przysiad-goblet", NULL,"active",1,25,15,3,30,NOW(),NOW()),
("Ściąganie liny wyciągu górnego do klatki","sciaganie-liny-wyciagu-gornego-do-klatki", NULL,"active",1,40,15,4,60,NOW(),NOW()),
("Wyciskanie sztangi","wyciskanie-sztangi", NULL,"active",1,60,15,3,120,NOW(),NOW()),
("Wyciskanie hantli na ławce prostej","wyciskanie-hantli-na-lawce-prostej", NULL,"active",1,25,15,4,90,NOW(),NOW()),
("Podnoszenie hantla nad głowę","podnoszenie-hantla-nad-glowe", NULL,"active",1,20,10,2,30,NOW(),NOW()),
("Wyciskanie hantla jednorącz w półklęku","wyciskanie-hantla-jednoracz-w-polkleku", NULL,"active",1,12,15,2,60,NOW(),NOW()),
("Martwy ciąg ze sztangą","martwy-ciag-ze-sztanga", NULL,"active",1,40,15,3,90,NOW(),NOW()),
("Martwy ciąg ze sztangą prostokątną","martwy-ciag-ze-sztanga-prostokatna", NULL,"active",1,30,15,3,60,NOW(),NOW()),
("T-pose z hantlami","t-pose-z-hantlami", NULL,"active",1,12,10,2,30,NOW(),NOW()),
("Rumuński martwy ciąg","rumunski-martwy-ciag", NULL,"active",1,12,15,3,60,NOW(),NOW()),
("Przyciąganie lin do twarzy","przyciaganie-lin-do-twarzy", NULL,"active",2,35,15,3,90,NOW(),NOW()),
("Wiosłowanie hantlami w oparciu o ławkę","wioslowanie-hantlami-w-oparciu-o-lawke", NULL,"active",2,12,20,3,60,NOW(),NOW()),
("Wyciskanie hantlami na ławce skośnej (rozpiętki)","wyciskanie-hantlami-na-lawce-skosnej-rozpietki", NULL,"active",2,12,20,3,60,NOW(),NOW()),
("Pompki z hantlami","pompki-z-hantlami", NULL,"active",2,12,15,3,60,NOW(),NOW()),
("Podciąganie się podchwytem","podciaganie-sie-podchwytem", NULL,"active",3,NULL,15,2,60,NOW(),NOW()),
("Odpychanie się na drabince (dipy)","odpychanie-sie-na-drabince-dipy", "można dodać pas z obciążeniem","active",3,NULL,15,4,60,NOW(),NOW()),
("Arnoldziki","arnoldziki", NULL,"active",3,10,25,4,30,NOW(),NOW()),
("Żuraw pod drabinką z matą","zuraw-pod-drabinka-z-mata", "można użyć gumy treningowej, aby ułatwić ćwiczenie","active",4,NULL,12,2,60,NOW(),NOW()),
("Prostowanie łydek na drabince","prostowanie-lydek-na-drabince", "przy pomocy stepa","active",4,NULL,25,4,60,NOW(),NOW()),
("Klękanie z jedną nogą na ławce (przysiad bułgarski)","klekanie-z-jedna-noga-na-lawce-przysiad-bulgarski", NULL,"active",4,12,12,4,60,NOW(),NOW());